### ISSUE TITLE
帮助文档有几个问题

### ISSUE THREAD

**Issue by SongZihuan** [pyecharts/website#44]
### 问题1：地图的import问题
![地图问题](https://github.com/SuperH-0630/Picture/raw/master/2020/02/07/2020022702.png)  
导入Faker得改成  
```from pyecharts.faker import Faker```   
### 问题2：帮助文档参数名和实际参数名不一致
![帮助文档](https://github.com/SuperH-0630/Picture/raw/master/2020/02/07/2020022700.png)  
![实际参数](https://github.com/SuperH-0630/Picture/raw/master/2020/02/07/2020022701.png)  
不少图有这个问题，这里列举的是Line，包括散点图等图均有这个问题
### 问题3：散点图的demo没有导入JsCode
![帮助文档 Scatter-多维度数据](https://github.com/SuperH-0630/Picture/raw/master/2020/02/07/2020022704.png)

**Comment by chenjiandongx** [comment]
@SuperH-0630 https://github.com/pyecharts/website/pull/45
