### ISSUE TITLE
Compatibility issues with Django 4.0

### ISSUE THREAD

**Issue by DanielWang123321** [pyecharts/website#56]
https://github.com/pyecharts/website/blob/master/zh-cn/web_django.md

This method does not work with Django later than V4.0
`from django.conf.urls import include, url`

For Django later than V4.0, could work with
```
from django.urls import include
from django.urls import re_path as url
```

Reference 
https://forum.djangoproject.com/t/django-4-0-url-import-error/11065

**Comment by sunhailin-Leo** [comment]
@DanielWang123321 
* Fixed: https://github.com/pyecharts/website/commit/746691c61f4724fe0752dfb81bdd6bccbaef6821
