### ISSUE TITLE
缺少 MapGlobe 对象文档

### ISSUE THREAD

**Issue by onemade** [pyecharts/website#62]
问题
MapGlobe 只有[范例代码](https://gallery.pyecharts.org/#/MapGlobe/map_globe_base)，未找到详细的说明文档。想知道如何设置3D地球的初始位置、角度及旋转速度，是否可通过程序控制地球中心视点的自动切换？

运行环境（系统环境及 pyecharts 版本）
pyecharts 2.0.3

代码及截图
https://gallery.pyecharts.org/#/MapGlobe/map_globe_base

**Comment by sunhailin-Leo** [comment]
@onemade 
* Reference here: https://pyecharts.org/#/zh-cn/geography_charts?id=map%ef%bc%9a%e5%9c%b0%e5%9b%be
