### ISSUE TITLE
页面链接失效

### ISSUE THREAD

**Issue by he-zhiyuan** [pyecharts/website#67]
contribution.md文件中的链接已经失效，无法访问：
https://github.com/pyecharts/pyecharts-user-case

**Comment by sunhailin-Leo** [comment]
@he-weilai 
* that repo is outdated

**Comment by he-zhiyuan** [comment]
@sunhailin-Leo OK,but don't you need to delete this link

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo OK,but don't you need to delete this link

* You can delete it if you have time to make pr. 😄

**Comment by he-zhiyuan** [comment]
@sunhailin-Leo OK, it's my pleasure.
