### ISSUE TITLE
Quick start English version image does not match code

### ISSUE THREAD

**Issue by he-zhiyuan** [pyecharts/website#69]
I found that the image and code on the English version of the Quick Start page do not match. Do you need me to regenerate the corresponding image? The text on the image should be in English
now:
![image](https://github.com/pyecharts/website/assets/109327586/263257b8-06eb-4702-8450-7958a8510b1c)
generate based on code：
![image](https://github.com/pyecharts/website/assets/109327586/b35b457e-3349-4cbe-8360-8022a993d0f1)

**Comment by sunhailin-Leo** [comment]
@he-weilai 
* I think it doesn`t matter. 😄

**Comment by sunhailin-Leo** [comment]
@he-weilai 
* You can check the configuration difference between the website and the source code.
